#!/bin/bash
clear

function pasang_domain() {
clear
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m            CHANGE HOST DOMAIN          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e " Sebelum Ganti Domain Harap Pointing Dulu Ip Vps Kalian"
    echo -e ""
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    read -rp " INPUT YOUR DOMAIN : " -e pp
    if [ -z $pp ]; then
        echo -e "
        Tidak ada domain yang di input"
    else
    echo "$pp" > /etc/xray/domain
    echo $pp > /root/domain
        echo "IP=$pp" > /var/lib/ipvps.conf
    fi
}


function pasang_ssl() {
    green "Pasang SSL"
    sleep 1
    rm -rf /etc/xray/xray.key
    rm -rf /etc/xray/xray.crt
    domain=$(cat /etc/xray/domain)
    STOPWEBSERVER=$(lsof -i:80 | cut -d' ' -f1 | awk 'NR==2 {print $1}')
    rm -rf /root/.acme.sh
    mkdir /root/.acme.sh
    systemctl stop $STOPWEBSERVER
    systemctl stop nginx
    systemctl stop haproxy
    curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
    chmod +x /root/.acme.sh/acme.sh
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
    ~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
    chmod 777 /etc/xray/xray.key
    systemctl restart nginx
    systemctl restart xray
    systemctl restart haproxy
}
function notif_addhost() {
    green "Notif AddHost Tele"
    sleep 2
    CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>──────────────────────</code>
<b>           SUCCESFULLY NOTIF</b>
<code>──────────────────────</code>
<b>              Add New Domain</b>
<code>──────────────────────</code>
<b>IP VPS    :</b> <code>$MYIP </code>
<b>DOMAIN :</b> <code>$pp</code>
<code>──────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
pasang_domain
pasang_ssl
notif_addhost

sleep 2
clear
menu